// get all categories
GET http://localhost:8000/users/ HTTP/1.1 



### add a user 

POST http://localhost:8000/users/ HTTP/1.1 
Content-Type: application/json

{
    "Name": "John Doe",
    "Username": "jj",
    "Password": "jj",
    "Role": "customer",
    "Phonenumber": "1234567890" 
}

### login request
POST http://localhost:8000/login/ HTTP/1.1
Content-Type: application/json

{
    "Username": "jj",
    "Password": "test"
}

### add a payment account to a user. 
POST http://localhost:8000/PaymentAccount/ HTTP/1.1
Content-Type: application/json

{ 
    "Address" : "1234 west test street",
    "Card_number":"1234-1234-1234-1234",
    "Exp_date":"04/20",
    "User": 1
}

### get a payment account by user name 

GET http://localhost:8000/PaymentAccount/1 HTTP/1.1

### add a layout to the database

POST http://localhost:8000/layouts/ HTTP/1.1
Content-Type: application/json

{
    "Name": "Split",
    "Discription": "For maximum comfort and ergonomics",
    "Price": 135.00
}


### GET ALL THE LAYOUTS

GET http://localhost:8000/layouts/ HTTP/1.1

### CREATE A SERVICE ENTRY

POST http://localhost:8000/services/ HTTP/1.1
Content-Type: application/json

{
    "Name": "No thank you", 
    "Discription": "I don't need any services.",
    "Price": 0
}


### GET ALL THE SERVICES 

GET http://localhost:8000/services/ HTTP/1.1

### CREATE A EXTRA 
POST http://localhost:8000/extras/ HTTP/1.1
Content-Type: application/json

{
    "Name": "No thank you ", 
    "Discription": "I don't need anything extra.",
    "Price": 0
}

### GET ALL THE EXTRAS
GET http://localhost:8000/extras/ HTTP/1.1


### CREATE A SWITCH LISTING 

POST http://localhost:8000/switches/ HTTP/1.1
Content-Type: application/json

{
    "Name": "Mx Cherry Brown", 
    "Discription": "Jack of all trades between typing and gaming",
    "Price": 30.00,
    "Feel": "Slight Bump", 
    "Noise": "Fairly Quiet"
}


### GET ALL SWITCHES 
GET http://localhost:8000/switches/ HTTP/1.1


### CREATE
POST http://localhost:8000/build/ HTTP/1.1
Content-Type: application/json

{
    "Name": "custom 1",
    "Layout": 1, 
    "Switch": 1,
    "Services": 1,
    "Extras": 1
}


### GET ALL SWITCHES 
GET http://localhost:8000/build/ HTTP/1.1

### Payment 

POST http://localhost:8000/payment/ HTTP/1.1

### Get All orders

GET http://localhost:8000/orders/ HTTP/1.1