# Generated by Django 3.2.5 on 2021-07-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=250)),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=250)),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=250)),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Switches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=250)),
                ('Price', models.FloatField()),
                ('Feel', models.CharField(max_length=20)),
                ('Noise', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=50)),
                ('Phonenumber', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Build_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KeyboardAPI.build')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KeyboardAPI.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=100)),
                ('Card_number', models.CharField(max_length=25)),
                ('Exp_date', models.CharField(help_text='00/00', max_length=5)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KeyboardAPI.user')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='Extras_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KeyboardAPI.extras'),
        ),
        migrations.AddField(
            model_name='build',
            name='Layout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KeyboardAPI.layout'),
        ),
        migrations.AddField(
            model_name='build',
            name='Services_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KeyboardAPI.services'),
        ),
        migrations.AddField(
            model_name='build',
            name='Switch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KeyboardAPI.switches'),
        ),
    ]
