# Generated by Django 3.2.5 on 2021-07-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KeyboardAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='Extras_id',
            new_name='Extras',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='Layout_id',
            new_name='Layout',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='Services_id',
            new_name='Services',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='Switch_id',
            new_name='Switch',
        ),
        migrations.RenameField(
            model_name='payment_account',
            old_name='User_id',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='shopping_cart',
            old_name='Build_id',
            new_name='Build',
        ),
        migrations.RenameField(
            model_name='shopping_cart',
            old_name='User_id',
            new_name='User',
        ),
    ]
