# Generated by Django 3.2.5 on 2021-07-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyboardAPI', '0002_auto_20210724_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
