# Generated by Django 3.2.5 on 2021-07-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyboardAPI', '0003_build_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='Build_name',
            field=models.CharField(default='custom', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='Price',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
    ]
