# Generated by Django 3.2.5 on 2021-07-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KeyboardAPI', '0004_auto_20210727_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('Build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KeyboardAPI.build')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KeyboardAPI.user')),
            ],
        ),
    ]
